import type { Cut } from "@/types";

// Local portfolio imagery. Sources are downloaded under /public/images/cuts.
export const CUTS: Cut[] = [
  {
    id: "cut-01",
    src: "/images/cuts/cut-01.jpg",
    alt: "Distinguished client in the chair getting his hair combed out by the barber",
    category: "fades",
    barberId: "john-h",
    caption: "Elder Statesman · Chairside Detail",
    size: "large",
  },
  {
    id: "cut-02",
    src: "/images/cuts/cut-02.jpg",
    alt: "Close-up of a fresh lineup",
    category: "lineups",
    barberId: "john-h",
    caption: "Razor Lineup · Side Profile",
    size: "medium",
  },
  {
    id: "cut-03",
    src: "/images/cuts/cut-03.jpg",
    alt: "Portrait of a sharp-dressed client with a clean fade and sculpted goatee",
    category: "beards",
    barberId: "devon-m",
    caption: "Tapered Fade · Goatee Sculpt",
    size: "medium",
  },
  {
    id: "cut-04",
    src: "/images/cuts/cut-04.jpg",
    alt: "Mid fade taper with a clean part",
    category: "fades",
    barberId: "john-h",
    caption: "Mid Fade · Hard Part",
    size: "large",
  },
  {
    id: "cut-05",
    src: "/images/cuts/cut-05.jpg",
    alt: "Classic taper cut, front-lit portrait",
    category: "fades",
    barberId: "marcus-l",
    caption: "Classic Taper",
    size: "medium",
  },
  {
    id: "cut-06",
    src: "/images/cuts/cut-06.jpg",
    alt: "Young client getting a clean fade with clippers in the barbershop chair",
    category: "kids",
    barberId: "carlos",
    caption: "Kids Fade · First Grade Ready",
    size: "medium",
  },
  {
    id: "cut-07",
    src: "/images/cuts/cut-07.jpg",
    alt: "Barber concentrating with clippers in hand mid-cut with his client",
    category: "lineups",
    barberId: "devon-m",
    caption: "Clipper Work · In The Chair",
    size: "large",
  },
  {
    id: "cut-08",
    src: "/images/cuts/cut-08.jpg",
    alt: "Platinum blonde color on a tapered cut",
    category: "color",
    barberId: "marcus-l",
    caption: "Platinum · Mid Taper",
    size: "medium",
  },
  {
    id: "cut-09",
    src: "/images/cuts/cut-09.jpg",
    alt: "Client smiling in warm studio light showing off long well-kept locs",
    category: "color",
    barberId: "andre-w",
    caption: "Locs · Signature Length",
    size: "large",
  },
  {
    id: "cut-10",
    src: "/images/cuts/cut-10.jpg",
    alt: "Hot towel steaming on a client's face",
    category: "beards",
    barberId: "devon-m",
    caption: "Hot Towel Ritual",
    size: "medium",
  },
  {
    id: "cut-11",
    src: "/images/cuts/cut-11.jpg",
    alt: "Young client relaxing in the barber chair as the neck strip is placed",
    category: "kids",
    barberId: "carlos",
    caption: "Kids Cut · In Good Hands",
    size: "medium",
  },
  {
    id: "cut-12",
    src: "/images/cuts/cut-12.jpg",
    alt: "Editorial side portrait of a short textured cut",
    category: "fades",
    barberId: "john-h",
    caption: "Short Textured · High Fade",
    size: "large",
  },
  {
    id: "cut-13",
    src: "/images/cuts/cut-13.jpg",
    alt: "Editorial black and white portrait of a client with short locs and round glasses",
    category: "color",
    barberId: "andre-w",
    caption: "Short Locs · Editorial",
    size: "medium",
  },
  {
    id: "cut-14",
    src: "/images/cuts/cut-14.jpg",
    alt: "Close-up of clippers mid-cut",
    category: "lineups",
    barberId: "john-h",
    caption: "Clipper Work · Detail",
    size: "medium",
  },
  {
    id: "cut-15",
    src: "/images/cuts/cut-15.jpg",
    alt: "Well-groomed long beard portrait",
    category: "beards",
    barberId: "devon-m",
    caption: "Sculpted Long Beard",
    size: "large",
  },
  {
    id: "cut-16",
    src: "/images/cuts/cut-16.jpg",
    alt: "Moody editorial portrait of a client smiling with his hand resting on his fresh cut",
    category: "fades",
    barberId: "marcus-l",
    caption: "Fresh Cut · In The Mood",
    size: "medium",
  },
];

export const CUT_FILTERS: { id: "all" | Cut["category"]; label: string }[] = [
  { id: "all", label: "All" },
  { id: "fades", label: "Fades" },
  { id: "lineups", label: "Lineups" },
  { id: "beards", label: "Beards" },
  { id: "kids", label: "Kids" },
  { id: "color", label: "Color" },
];
