import type { Cut } from "@/types";

// Local portfolio imagery. Sources are downloaded under /public/images/cuts.
export const CUTS: Cut[] = [
  {
    id: "cut-01",
    src: "/images/cuts/cut-01.jpg",
    alt: "Sharp skin fade on a client looking straight into the camera",
    category: "fades",
    barberId: "john-h",
    caption: "Skin Fade · Textured Top",
    size: "large",
  },
  {
    id: "cut-02",
    src: "/images/cuts/cut-02.jpg",
    alt: "Close-up of a fresh lineup",
    category: "lineups",
    barberId: "john-h",
    caption: "Razor Lineup · Side Profile",
    size: "medium",
  },
  {
    id: "cut-03",
    src: "/images/cuts/cut-03.jpg",
    alt: "Full beard shape and haircut combination",
    category: "beards",
    barberId: "devon-m",
    caption: "Full Beard · Lineup Finish",
    size: "medium",
  },
  {
    id: "cut-04",
    src: "/images/cuts/cut-04.jpg",
    alt: "Mid fade taper with a clean part",
    category: "fades",
    barberId: "john-h",
    caption: "Mid Fade · Hard Part",
    size: "large",
  },
  {
    id: "cut-05",
    src: "/images/cuts/cut-05.jpg",
    alt: "Classic taper cut, front-lit portrait",
    category: "fades",
    barberId: "marcus-l",
    caption: "Classic Taper",
    size: "medium",
  },
  {
    id: "cut-06",
    src: "/images/cuts/cut-06.jpg",
    alt: "Kid getting a fresh fade in the chair",
    category: "kids",
    barberId: "carlos",
    caption: "Kids Fade · First Grade Ready",
    size: "medium",
  },
  {
    id: "cut-07",
    src: "/images/cuts/cut-07.jpg",
    alt: "Barber executing a clean lineup with clippers",
    category: "lineups",
    barberId: "devon-m",
    caption: "Lineup In Progress",
    size: "large",
  },
  {
    id: "cut-08",
    src: "/images/cuts/cut-08.jpg",
    alt: "Platinum blonde color on a tapered cut",
    category: "color",
    barberId: "marcus-l",
    caption: "Platinum · Mid Taper",
    size: "medium",
  },
  {
    id: "cut-09",
    src: "/images/cuts/cut-09.jpg",
    alt: "Textured curly cut with faded sides",
    category: "fades",
    barberId: "andre-w",
    caption: "Curl Sponge · Bald Fade",
    size: "large",
  },
  {
    id: "cut-10",
    src: "/images/cuts/cut-10.jpg",
    alt: "Hot towel steaming on a client's face",
    category: "beards",
    barberId: "devon-m",
    caption: "Hot Towel Ritual",
    size: "medium",
  },
  {
    id: "cut-11",
    src: "/images/cuts/cut-11.jpg",
    alt: "Young client after a fresh haircut",
    category: "kids",
    barberId: "carlos",
    caption: "Kids Cut · All Smiles",
    size: "medium",
  },
  {
    id: "cut-12",
    src: "/images/cuts/cut-12.jpg",
    alt: "Editorial side portrait of a short textured cut",
    category: "fades",
    barberId: "john-h",
    caption: "Short Textured · High Fade",
    size: "large",
  },
  {
    id: "cut-13",
    src: "/images/cuts/cut-13.jpg",
    alt: "Locs pulled back after a maintenance appointment",
    category: "color",
    barberId: "andre-w",
    caption: "Locs · Retwist & Treatment",
    size: "medium",
  },
  {
    id: "cut-14",
    src: "/images/cuts/cut-14.jpg",
    alt: "Close-up of clippers mid-cut",
    category: "lineups",
    barberId: "john-h",
    caption: "Clipper Work · Detail",
    size: "medium",
  },
  {
    id: "cut-15",
    src: "/images/cuts/cut-15.jpg",
    alt: "Well-groomed long beard portrait",
    category: "beards",
    barberId: "devon-m",
    caption: "Sculpted Long Beard",
    size: "large",
  },
  {
    id: "cut-16",
    src: "/images/cuts/cut-16.jpg",
    alt: "Dramatic backlit portrait of a fresh haircut",
    category: "fades",
    barberId: "marcus-l",
    caption: "Editorial · Fresh Cut",
    size: "medium",
  },
];

export const CUT_FILTERS: { id: "all" | Cut["category"]; label: string }[] = [
  { id: "all", label: "All" },
  { id: "fades", label: "Fades" },
  { id: "lineups", label: "Lineups" },
  { id: "beards", label: "Beards" },
  { id: "kids", label: "Kids" },
  { id: "color", label: "Color" },
];
