import type { Review } from "@/types";

export const REVIEWS: Review[] = [
  {
    id: "r-mr-john",
    name: "Mr. John",
    stars: 5,
    when: "2 months ago",
    body: "Absolutely amazing!! I just moved to VA Alexandria area and was looking for a barber after going to one that didn't quite listen to my haircut directions. I looked up Ultimate Styles Barbershop and booked an appointment with Kareem and he did a great job, listened carefully and nailed exactly what I wanted.",
  },
  {
    id: "r-angel-abston",
    name: "Angel Abston",
    stars: 5,
    when: "2 months ago",
    localGuide: true,
    body: "Carlos is AMAZING! He cuts my 2 year old son's hair and it's always on point! He makes sure my son is comfortable, enjoying the experience, and goes with his flow. I appreciate his care, professionalism, attentiveness and I always love the results.",
  },
  {
    id: "r-walk-in",
    name: "Devin R.",
    stars: 5,
    when: "3 weeks ago",
    body: "Great service, excellent work, and short wait time as a walk-in. The atmosphere, staff, and location — outstanding. I came in on a Saturday not expecting much and left with one of the cleanest fades I've had in years.",
  },
  {
    id: "r-mike-b",
    name: "Mike B.",
    stars: 5,
    when: "1 month ago",
    body: "Been coming here for a year now. John H does my fade every two weeks and it's flawless every time. He actually talks to you, remembers what you asked for last time, and always gets the lineup right. Hard to find that kind of consistency.",
  },
  {
    id: "r-tasha",
    name: "Tasha D.",
    stars: 5,
    when: "5 weeks ago",
    badge: "Local Guide",
    localGuide: true,
    body: "Took my two sons in on a Saturday morning — five and seven years old. Carlos was so patient with my youngest who's usually a nightmare in the chair. Both of them came out with the sharpest cuts. We'll be regulars.",
  },
  {
    id: "r-eric-t",
    name: "Eric T.",
    stars: 5,
    when: "2 weeks ago",
    body: "The hot towel shave here is the real deal. Full ceremony — oil, steam, straight razor, balm. Walked out feeling like a different person. Devon knows exactly what he's doing and it shows.",
  },
  {
    id: "r-jamal",
    name: "Jamal P.",
    stars: 5,
    when: "1 month ago",
    body: "I drive in from DC. That should tell you everything. Nobody in the District gives a mid-fade like the guys at Ultimate Styles. Shop is clean, music is right, and they move you through fast without rushing the work.",
  },
  {
    id: "r-chris-w",
    name: "Chris W.",
    stars: 5,
    when: "3 months ago",
    body: "Came in for a beard shape-up before a wedding. Devon cleaned it up, evened the jawline, and finished with the straight razor. My fiancée actually noticed before I said anything. Ten out of ten.",
  },
  {
    id: "r-lina",
    name: "Lina K.",
    stars: 5,
    when: "6 weeks ago",
    body: "As a queer woman looking for a masculine cut, I was nervous about finding the right shop. John H was welcoming from the second I sat down, asked all the right questions, and delivered the exact look I've been chasing for years. This place is for everyone.",
  },
  {
    id: "r-marvin",
    name: "Marvin G.",
    stars: 5,
    when: "2 weeks ago",
    body: "Best barbershop in Alexandria, and it isn't close. Atmosphere is professional without being stiff, the barbers take their time, and the prices are fair for the quality. Book online — it saves you the wait.",
  },
  {
    id: "r-samuel",
    name: "Samuel O.",
    stars: 5,
    when: "1 week ago",
    body: "Marcus did a subtle gray blend on my beard and it came out looking natural — like it was always there. No brassy tones, no patches. True artist with color.",
  },
];
